export const cidadesBrasilNomeCurto = [
  "São Paulo",
  "Rio de Janeiro",
  "Belo Horizonte",
  "Salvador",
  "Fortaleza",
  "Brasília",
  "Curitiba",
  "Manaus",
  "Recife",
  "Porto Alegre",
  "Belém",
  "Goiânia",
  "Guarulhos",
  "Campinas",
  "São Luís",
  "São Gonçalo",
  "Maceió",
  "Duque de Caxias",
  "Natal",
  "Campo Grande",
  "Teresina",
  "São Bernardo",
  "João Pessoa",
  "Nova Iguaçu",
  "Santo André",
  "Osasco",
  "S. J. dos Campos",
  "Jaboatão",
  "Ribeirão Preto",
  "Uberlândia",
  "Sorocaba",
  "Contagem",
  "Aracaju",
  "Feira de Santana",
  "Cuiabá",
  "Joinville",
  "Juiz de Fora",
  "Londrina",
  "Aparecida",
  "Ananindeua",
  "Niterói",
  "Porto Velho",
  "Campos",
  "Belford Roxo",
  "Serra",
  "Caxias do Sul",
  "Vila Velha",
  "Florianópolis",
  "Macapá",
  "S. J. do Rio Preto",
  "Mauá",
  "Mogi das Cruzes",
  "Santos",
  "Diadema",
  "Betim",
  "Campina Grande",
  "Jundiaí",
  "Maringá",
  "Montes Claros",
  "Piracicaba",
  "Carapicuíba",
  "Olinda",
  "Cariacica",
  "Rio Branco",
  "Anápolis",
  "Bauru",
  "Vitória",
  "Caucaia",
  "Itaquaquecetuba",
  "São Vicente",
  "Caruaru",
  "Vitória da Conquista",
  "Blumenau",
  "Franca",
  "Ponta Grossa",
  "Petrolina",
  "Canoas",
  "Pelotas",
  "Ribeirão das Neves",
  "Paulista",
  "Uberaba",
  "Cascavel",
  "Guarujá",
  "Praia Grande",
  "Taubaté",
  "São José dos Pinhais",
  "Limeira",
  "Santarém",
  "Camaçari",
  "Palmas",
  "Suzano",
  "Mossoró",
  "Taboão da Serra",
  "Várzea Grande",
  "Sumaré",
  "Santa Maria",
  "Gravataí",
  "Marabá",
  "Gov. Valadares",
  "Barueri",
  "Embu das Artes",
  "Volta Redonda",
  "Ipatinga",
  "Parnamirim",
  "Imperatriz",
  "Foz do Iguaçu",
  "Viamão",
  "São Carlos",
  "Macaé",
  "Indaiatuba",
  "Cotia",
  "Novo Hamburgo",
  "São José",
  "Colombo",
  "Magé",
  "Itaboraí",
  "Americana",
  "S. J. de Meriti",
  "Dourados",
  "Sete Lagoas",
  "Rio Verde",
  "Divinópolis",
  "Marília",
  "Araraquara",
  "Jacareí",
  "Cabo Frio",
  "Presidente Prudente",
  "Itabuna",
  "Arapiraca",
  "Rondonópolis",
];

export const gerarDadosCidadesNomeCurto = () => {
  return cidadesBrasilNomeCurto.map((cidade) => {
    const baseValue = Math.floor(Math.random() * 10000) + 1000;
    const variation = Math.floor(Math.random() * 2000) - 500;

    return {
      cidade,
      valorAnoAnterior: baseValue,
      valorReal: baseValue + variation,
    };
  });
};
