export const cidadesBrasil = [
  "São Luís do Paraitinga/SP",
  "São Francisco de Assis de Itabapoana/RJ",
  "Santana do Livramento da Boa Vista/RS",
  "São Sebastião do Alto da Serra Grande/RJ",
  "Nossa Senhora do Livramento do Monte Alto/MT",
  "São Francisco do Conde da Bahia de Todos os Santos/BA",
  "Presidente Bernardes/SP",
  "Santana de Parnaíba/SP",
  "São José do Rio Preto/SP",
  "Piedade de Caratinga/MG",
  "Francisco Sá/MG",
  "Dona Euzébia/MG",
  "Senador José Bento/MG",
  "Espírito Santo do Pinhal/SP",
  "Santa Rita do Sapucaí/MG",
  "São Sebastião da Grama/SP",
  "Aparecida d'Oeste/SP",
  "Presidente Epitácio/SP",
  "Fernandópolis/SP",
  "São Miguel Arcanjo/SP",
  "Vargem Grande Paulista/SP",
  "Santana do Livramento/RS",
  "Santa Cruz do Sul/RS",
  "São Francisco do Sul/SC",
  "Balneário Piçarras/SC",
  "Presidente Getúlio/SC",
  "Santo Amaro da Imperatriz/SC",
  "Águas de Lindóia/SP",
  "Campos do Jordão/SP",
  "Embu-Guaçu/SP",
  "Ferraz de Vasconcelos/SP",
  "Francisco Morato/SP",
  "Santana do Paraíso/MG",
  "São João del-Rei/MG",
  "São Sebastião do Paraíso/MG",
  "Estrela d'Oeste/SP",
  "Pereira Barreto/SP",
  "Presidente Venceslau/SP",
  "Santa Bárbara d'Oeste/SP",
  "Santa Fé do Sul/SP",
  "Santo Antônio de Posse/SP",
  "São Caetano do Sul/SP",
  "Barra do Piraí/RJ",
  "Miracema do Tocantins/TO",
  "São Gabriel da Cachoeira/AM",
  "Senador José Porfírio/PA",
  "Francisco Beltrão/PR",
  "Almirante Tamandaré/PR",
  "São José dos Pinhais/PR",

  // São Paulo
  "São Paulo/SP",
  "Campinas/SP",
  "Guarulhos/SP",
  "São Bernardo do Campo/SP",
  "Santo André/SP",
  "Osasco/SP",
  "Sorocaba/SP",
  "Ribeirão Preto/SP",
  "São José dos Campos/SP",
  "Santos/SP",
  "Mauá/SP",
  "Diadema/SP",
  "Jundiaí/SP",
  "Carapicuíba/SP",
  "Piracicaba/SP",
  "Bauru/SP",
  "Itaquaquecetuba/SP",
  "São Vicente/SP",
  "Franca/SP",
  "Guarujá/SP",
  "Taubaté/SP",
  "Limeira/SP",
  "Suzano/SP",
  "Taboão da Serra/SP",
  "Sumaré/SP",
  "Barueri/SP",
  "Embu das Artes/SP",
  "São Carlos/SP",
  "Marília/SP",
  "Indaiatuba/SP",
  "Cotia/SP",
  "Americana/SP",
  "Jacareí/SP",
  "Araraquara/SP",
  "Itu/SP",
  "Presidente Prudente/SP",
  "Guaratinguetá/SP",
  "Mogi das Cruzes/SP",
  "Atibaia/SP",
  "Araçatuba/SP",

  // Rio de Janeiro
  "Rio de Janeiro/RJ",
  "São Gonçalo/RJ",
  "Duque de Caxias/RJ",
  "Nova Iguaçu/RJ",
  "Niterói/RJ",
  "Belford Roxo/RJ",
  "São João de Meriti/RJ",
  "Campos dos Goytacazes/RJ",
  "Petrópolis/RJ",
  "Volta Redonda/RJ",
  "Magé/RJ",
  "Macaé/RJ",
  "Itaboraí/RJ",
  "Cabo Frio/RJ",
  "Nova Friburgo/RJ",
  "Barra Mansa/RJ",
  "Angra dos Reis/RJ",
  "Mesquita/RJ",
  "Nilópolis/RJ",
  "Teresópolis/RJ",
  "Maricá/RJ",
  "Queimados/RJ",
  "Resende/RJ",
  "Araruama/RJ",
  "Itaguaí/RJ",

  // Minas Gerais
  "Belo Horizonte/MG",
  "Uberlândia/MG",
  "Contagem/MG",
  "Juiz de Fora/MG",
  "Betim/MG",
  "Montes Claros/MG",
  "Ribeirão das Neves/MG",
  "Uberaba/MG",
  "Governador Valadares/MG",
  "Ipatinga/MG",
  "Sete Lagoas/MG",
  "Divinópolis/MG",
  "Santa Luzia/MG",
  "Ibirité/MG",
  "Poços de Caldas/MG",
  "Patos de Minas/MG",
  "Teófilo Otoni/MG",
  "Sabará/MG",
  "Pouso Alegre/MG",
  "Barbacena/MG",
  "Varginha/MG",
  "Conselheiro Lafaiete/MG",
  "Araguari/MG",
  "Itabira/MG",
  "Passos/MG",

  // Bahia
  "Salvador/BA",
  "Feira de Santana/BA",
  "Vitória da Conquista/BA",
  "Camaçari/BA",
  "Itabuna/BA",
  "Juazeiro/BA",
  "Lauro de Freitas/BA",
  "Ilhéus/BA",
  "Jequié/BA",
  "Teixeira de Freitas/BA",
  "Alagoinhas/BA",
  "Barreiras/BA",
  "Paulo Afonso/BA",
  "Simões Filho/BA",
  "Santo Antônio de Jesus/BA",
  "Valença/BA",
  "Candeias/BA",
  "Guanambi/BA",
  "Jacobina/BA",
  "Serrinha/BA",
  "Senhor do Bonfim/BA",
  "Dias d'Ávila/BA",
  "Luís Eduardo Magalhães/BA",
  "Santo Amaro/BA",
  "Euclides da Cunha/BA",
  "Bom Jesus da Lapa/BA",
  "Castro Alves/BA",
  "Madre de Deus/BA",
  "Santa Maria da Vitória/BA",

  // Paraná
  "Curitiba/PR",
  "Londrina/PR",
  "Maringá/PR",
  "Ponta Grossa/PR",
  "Cascavel/PR",
  "São José dos Pinhais/PR",
  "Foz do Iguaçu/PR",
  "Colombo/PR",
  "Guarapuava/PR",
  "Paranaguá/PR",
  "Araucária/PR",
  "Toledo/PR",
  "Apucarana/PR",
  "Pinhais/PR",
  "Campo Largo/PR",
  "Almirante Tamandaré/PR",
  "Umuarama/PR",
  "Piraquara/PR",
  "Cambé/PR",
  "Pato Branco/PR",
  "Francisco Beltrão/PR",
  "Fazenda Rio Grande/PR",
  "Paranavaí/PR",
  "Sarandi/PR",
  "Telêmaco Borba/PR",

  // Rio Grande do Sul
  "Porto Alegre/RS",
  "Caxias do Sul/RS",
  "Pelotas/RS",
  "Canoas/RS",
  "Santa Maria/RS",
  "Gravataí/RS",
  "Viamão/RS",
  "Novo Hamburgo/RS",
  "São Leopoldo/RS",
  "Rio Grande/RS",
  "Alvorada/RS",
  "Passo Fundo/RS",
  "Sapucaia do Sul/RS",
  "Uruguaiana/RS",
  "Santa Cruz do Sul/RS",
  "Cachoeirinha/RS",
  "Bagé/RS",
  "Bento Gonçalves/RS",
  "Erechim/RS",
  "Guaíba/RS",
  "Santana do Livramento/RS",
  "Lajeado/RS",
  "Ijuí/RS",
  "Alegrete/RS",
  "Novo Hamburgo/RS",

  // Santa Catarina
  "Florianópolis/SC",
  "Joinville/SC",
  "Blumenau/SC",
  "São José/SC",
  "Criciúma/SC",
  "Chapecó/SC",
  "Itajaí/SC",
  "Jaraguá do Sul/SC",
  "Lages/SC",
  "Palhoça/SC",
  "Balneário Camboriú/SC",
  "Brusque/SC",
  "Tubarão/SC",
  "São Bento do Sul/SC",
  "Caçador/SC",
  "Camboriú/SC",
  "Navegantes/SC",
  "Concórdia/SC",
  "Rio do Sul/SC",
  "Araranguá/SC",
  "Gaspar/SC",
  "Biguaçu/SC",
  "Indaial/SC",
  "Itapema/SC",
  "Mafra/SC",
  "Canoinhas/SC",
  "Içara/SC",
  "Videira/SC",
  "Ibirama/SC",
  "Tijucas/SC",

  // Pernambuco
  "Recife/PE",
  "Jaboatão dos Guararapes/PE",
  "Olinda/PE",
  "Caruaru/PE",
  "Petrolina/PE",
  "Paulista/PE",
  "Cabo de Santo Agostinho/PE",
  "Camaragibe/PE",
  "Garanhuns/PE",
  "Vitória de Santo Antão/PE",
  "Igarassu/PE",
  "São Lourenço da Mata/PE",
  "Abreu e Lima/PE",
  "Santa Cruz do Capibaribe/PE",
  "Ipojuca/PE",
  "Serra Talhada/PE",
  "Araripina/PE",
  "Gravatá/PE",
  "Carpina/PE",
  "Goiana/PE",

  // Ceará
  "Fortaleza/CE",
  "Caucaia/CE",
  "Juazeiro do Norte/CE",
  "Maracanaú/CE",
  "Sobral/CE",
  "Crato/CE",
  "Itapipoca/CE",
  "Maranguape/CE",
  "Iguatu/CE",
  "Quixadá/CE",
  "Canindé/CE",
  "Pacatuba/CE",
  "Aquiraz/CE",
  "Quixeramobim/CE",
  "Crateús/CE",
  "Cascavel/CE",
  "Horizonte/CE",
  "Russas/CE",
  "Aracati/CE",
  "Limoeiro do Norte/CE",

  // Pará
  "Belém/PA",
  "Ananindeua/PA",
  "Santarém/PA",
  "Marabá/PA",
  "Castanhal/PA",
  "Parauapebas/PA",
  "Itaituba/PA",
  "Cametá/PA",
  "Bragança/PA",
  "Abaetetuba/PA",
  "Marituba/PA",
  "Altamira/PA",
  "Tucuruí/PA",
  "Benevides/PA",
  "Barcarena/PA",

  // Goiás
  "Goiânia/GO",
  "Aparecida de Goiânia/GO",
  "Anápolis/GO",
  "Rio Verde/GO",
  "Luziânia/GO",
  "Águas Lindas de Goiás/GO",
  "Valparaíso de Goiás/GO",
  "Trindade/GO",
  "Formosa/GO",
  "Novo Gama/GO",
  "Itumbiara/GO",
  "Senador Canedo/GO",
  "Catalão/GO",
  "Jataí/GO",
  "Planaltina/GO",

  // Maranhão
  "São Luís/MA",
  "Imperatriz/MA",
  "São José de Ribamar/MA",
  "Timon/MA",
  "Caxias/MA",
  "Codó/MA",
  "Paço do Lumiar/MA",
  "Açailândia/MA",
  "Bacabal/MA",
  "Balsas/MA",

  // Espírito Santo
  "Vitória/ES",
  "Vila Velha/ES",
  "Serra/ES",
  "Cariacica/ES",
  "Cachoeiro de Itapemirim/ES",
  "Linhares/ES",
  "São Mateus/ES",
  "Colatina/ES",
  "Guarapari/ES",
  "Aracruz/ES",

  // Paraíba
  "João Pessoa/PB",
  "Campina Grande/PB",
  "Santa Rita/PB",
  "Patos/PB",
  "Bayeux/PB",
  "Sousa/PB",
  "Cajazeiras/PB",
  "Guarabira/PB",
  "Mamanguape/PB",
  "Cabedelo/PB",
  "São João do Rio do Peixe/PB",
  "Conceição do Coité/BA",
  "Governador Mangabeira/BA",
  "São Francisco do Conde/BA",
  "São Sebastião do Passé/BA",

  // Amazonas
  "Manaus/AM",
  "Parintins/AM",
  "Itacoatiara/AM",
  "Manacapuru/AM",
  "Coari/AM",
  "Tefé/AM",
  "Tabatinga/AM",
  "Maués/AM",
  "Humaitá/AM",
  "Iranduba/AM",
  "São Paulo de Olivença/AM",
  "Benjamin Constant/AM",
  "Santo Antônio do Içá/AM",

  // Mato Grosso
  "Cuiabá/MT",
  "Várzea Grande/MT",
  "Rondonópolis/MT",
  "Sinop/MT",
  "Tangará da Serra/MT",
  "Cáceres/MT",
  "Sorriso/MT",
  "Lucas do Rio Verde/MT",
  "Barra do Garças/MT",
  "Primavera do Leste/MT",

  // Rio Grande do Norte
  "Natal/RN",
  "Mossoró/RN",
  "Parnamirim/RN",
  "São Gonçalo do Amarante/RN",
  "Macaíba/RN",
  "Ceará-Mirim/RN",
  "Caicó/RN",
  "Açu/RN",
  "Currais Novos/RN",
  "Nova Cruz/RN",

  // Mato Grosso do Sul
  "Campo Grande/MS",
  "Dourados/MS",
  "Três Lagoas/MS",
  "Corumbá/MS",
  "Ponta Porã/MS",
  "Naviraí/MS",
  "Nova Andradina/MS",
  "Sidrolândia/MS",
  "Aquidauana/MS",
  "Maracaju/MS",

  // Alagoas
  "Maceió/AL",
  "Arapiraca/AL",
  "Palmeira dos Índios/AL",
  "Rio Largo/AL",
  "União dos Palmares/AL",
  "Penedo/AL",
  "São Miguel dos Campos/AL",
  "Santana do Ipanema/AL",
  "Delmiro Gouveia/AL",
  "Coruripe/AL",
  "São Luís do Quitunde/AL",
  "Matriz de Camaragibe/AL",

  // Piauí
  "Teresina/PI",
  "Parnaíba/PI",
  "Picos/PI",
  "Piripiri/PI",
  "Floriano/PI",
  "Campo Maior/PI",
  "Barras/PI",
  "Altos/PI",
  "Esperantina/PI",
  "Pedro II/PI",
  "São Raimundo Nonato/PI",
  "Miguel Alves/PI",
  "José de Freitas/PI",

  // Sergipe
  "Aracaju/SE",
  "Nossa Senhora do Socorro/SE",
  "Lagarto/SE",
  "Itabaiana/SE",
  "Estância/SE",
  "São Cristóvão/SE",
  "Simão Dias/SE",
  "Propriá/SE",
  "Tobias Barreto/SE",
  "Barra dos Coqueiros/SE",

  // Distrito Federal
  "Brasília/DF",
  "Ceilândia/DF",
  "Samambaia/DF",
  "Taguatinga/DF",
  "Planaltina/DF",

  // Tocantins
  "Palmas/TO",
  "Araguaína/TO",
  "Gurupi/TO",
  "Porto Nacional/TO",
  "Paraíso do Tocantins/TO",

  // Rondônia
  "Porto Velho/RO",
  "Ji-Paraná/RO",
  "Ariquemes/RO",
  "Vilhena/RO",
  "Cacoal/RO",

  // Acre
  "Rio Branco/AC",
  "Cruzeiro do Sul/AC",
  "Sena Madureira/AC",
  "Tarauacá/AC",
  "Feijó/AC",

  // Roraima
  "Boa Vista/RR",
  "Rorainópolis/RR",
  "Caracaraí/RR",
  "Mucajaí/RR",
  "Alto Alegre/RR",

  // Amapá
  "Macapá/AP",
  "Santana/AP",
  "Laranjal do Jari/AP",
  "Oiapoque/AP",
  "Mazagão/AP",
];

export const gerarDadosCidades = () => {
  return cidadesBrasil.map((cidade) => {
    const baseValue = Math.floor(Math.random() * 10000) + 1000;
    const variation = Math.floor(Math.random() * 2000) - 500;

    return {
      cidade,
      valorAnoAnterior: baseValue,
      valorReal: baseValue + variation,
    };
  });
};
