#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx eslint . --max-warnings=0

if [ $? -ne 0 ]; then
  echo "❌ ESLint encontrou erro(s). Commit abortado."
  exit 1
fi
echo "✅ ESLint passou sem erros. Commit permitido."