#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Roda eslint em todo o projeto, bloqueia se tiver erro
eslint . --max-warnings=0

if [ $? -ne 0 ]; then
  echo "❌ ESLint encontrou erro(s). Commit abortado."
  exit 1
fi
