name: CI on Dev

on:
  push:
    branches:
      - ci/eslint-deploy-pipeline
  workflow_dispatch: 

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build CSS (Tailwind)
        run: npm run build-css

      - name: Build JS (Tsup)
        run: npm run build
