name: CI & Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Tipo de versionamento (patch, minor, major)'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
      publish:
        description: 'Publicar no npm? (y/N)'
        required: false
        type: choice
        options:
          - y
          - N

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build CSS (Tailwind)
        run: npm run build-css

      - name: Build JS (Tsup)
        run: npm run build


  release:
    environment: prd
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version_type != '' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: get-current-npm-version
        id: current-package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Versionamento manual
        run: |
          npm version ${{ github.event.inputs.version_type }}

      - name: get-new-npm-version
        id: new-package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Exibir versão atual
        run: |
          echo "Nova versão: ${{ steps.new-package-version.outputs.current-version }}"

      - name: Commit version changes
        run: |
          git add package.json package-lock.yaml 2>/dev/null || git add package.json
          git commit -m "chore: bump version to v${{ steps.current-package-version.outputs.current-version }}")" || echo "No changes to commit"

      - name: Build package
        run: npm run build

      - name: Publicar no npm (condicional)
        if: ${{ github.event.inputs.publish == 'y' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
        run: npm publish --no-git-checks

      - name: Reverter versão se não publicar
        if: ${{ github.event.inputs.publish != 'y' }}
        run: |
          git restore package.json
          echo "Versão revertida - alterações não foram commitadas"